name: Regresion E2E - AppBarber 2.0

on:
  push:
    branches: [ main, develop, feat/testNG ]
  pull_request:
    branches: [ main , develop]

jobs:
  ejecutar-pruebas-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio en la nube
      uses: actions/checkout@v4

    - name: Configurar Java 17 (JDK Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Compilar proyecto de pruebas
      run: |
        cd tests
        mvn compile
    
    - name: Instalar dependencias del sistema de Playwright (Vía NPX)
      run: npx playwright install-deps

    - name: Ejecutar Suite de TestNG (POM) contra Render
      run: |
        cd tests
        mvn test -Durl.base="https://appbarber-2-0.onrender.com" -Dbrowser.headless=true

    - name: Almacenar reporte HTML de resultados
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-ejecucion-testng
        path: tests/target/surefire-reports/
